# Generated by Django 2.2.9 on 2020-07-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messier_objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messierobject',
            name='declination',
        ),
        migrations.RemoveField(
            model_name='messierobject',
            name='right_ascension',
        ),
    ]
