# Generated by Django 2.2.9 on 2020-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messier_objects', '0005_auto_20200723_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messierobject',
            name='messier_number',
            field=models.IntegerField(unique=True),
        ),
    ]
