# Generated by Django 3.0.8 on 2020-07-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messier_objects', '0006_auto_20200724_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='messierobject',
            name='captured',
            field=models.BooleanField(default=False),
        ),
    ]
