# Generated by Django 3.0.8 on 2020-07-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messier_objects', '0007_messierobject_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messierobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='messier_objects'),
        ),
    ]
