# Generated by Django 3.0.8 on 2020-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messier_objects', '0010_messierobject_capture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messierobject',
            name='apparent_magnitude',
            field=models.FloatField(null=True),
        ),
    ]
