# Generated by Django 3.0.8 on 2020-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system_objects', '0003_auto_20200728_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystemobject',
            name='parent_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
