# Generated by Django 3.0.8 on 2020-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsteroidCometMeteorObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=255)),
                ('size_km', models.FloatField(blank=True, max_length=255)),
                ('discovery_date', models.DateTimeField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asteroid_comet_meteor')),
                ('captured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
