# Generated by Django 3.0.8 on 2020-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids_comets_meteors', '0002_auto_20200728_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidcometmeteorobject',
            name='size_km',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
