# Generated by Django 3.0.8 on 2020-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids_comets_meteors', '0003_auto_20200728_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidcometmeteorobject',
            name='discovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asteroidcometmeteorobject',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asteroidcometmeteorobject',
            name='size_km',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
