# Generated by Django 3.0.8 on 2020-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids_comets_meteors', '0006_auto_20200729_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidcometmeteorobject',
            name='capture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
